"""Model card generator for AI system documentation.

Creates structured model cards following industry best practices
(inspired by Google's Model Cards for Model Reporting).
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

import yaml
from jinja2 import Environment, FileSystemLoader, select_autoescape


MODEL_CARD_TEMPLATE = """# Model Card: {{ model.name }}

**Version:** {{ model.version }}
**Date:** {{ model.date }}
**Owner:** {{ model.owner }}

---

## Model Details

| Field | Value |
|-------|-------|
| **Model Name** | {{ model.name }} |
| **Version** | {{ model.version }} |
| **Type** | {{ model.model_type }} |
| **Architecture** | {{ model.architecture }} |
| **Framework** | {{ model.framework }} |
| **License** | {{ model.license }} |

### Description

{{ model.description }}

---

## Intended Use

### Primary Use Cases
{% for use in model.intended_uses %}
- {{ use }}
{% endfor %}

### Out-of-Scope Uses
{% for use in model.out_of_scope_uses %}
- {{ use }}
{% endfor %}

### Target Users
{% for user in model.target_users %}
- {{ user }}
{% endfor %}

---

## Training Data

{{ model.training_data_description }}

| Property | Value |
|----------|-------|
{% for key, value in model.training_data_stats.items() %}
| {{ key }} | {{ value }} |
{% endfor %}

---

## Evaluation

### Metrics
{% for metric in model.metrics %}
| {{ metric.name }} | {{ metric.value }} | {{ metric.description }} |
{% endfor %}

### Performance by Group
{% if model.performance_by_group %}
| Group | Metric | Value |
|-------|--------|-------|
{% for group in model.performance_by_group %}
| {{ group.group }} | {{ group.metric }} | {{ group.value }} |
{% endfor %}
{% else %}
No disaggregated performance data available.
{% endif %}

---

## Ethical Considerations

### Known Limitations
{% for limitation in model.limitations %}
- {{ limitation }}
{% endfor %}

### Bias & Fairness
{% for item in model.bias_considerations %}
- {{ item }}
{% endfor %}

### Risk Mitigations
{% for mitigation in model.risk_mitigations %}
- {{ mitigation }}
{% endfor %}

---

## Maintenance

| Field | Value |
|-------|-------|
| **Owner** | {{ model.owner }} |
| **Contact** | {{ model.contact }} |
| **Update Frequency** | {{ model.update_frequency }} |
| **Last Updated** | {{ model.date }} |

---

*Generated by AI Governance Framework — Model Card Generator*
"""


@dataclass
class MetricInfo:
    name: str
    value: str
    description: str = ""


@dataclass
class GroupPerformance:
    group: str
    metric: str
    value: str


@dataclass
class ModelCardData:
    name: str
    version: str = "1.0"
    date: str = field(default_factory=lambda: datetime.now().strftime("%Y-%m-%d"))
    owner: str = ""
    model_type: str = ""
    architecture: str = ""
    framework: str = ""
    license: str = "Proprietary"
    description: str = ""
    intended_uses: list[str] = field(default_factory=list)
    out_of_scope_uses: list[str] = field(default_factory=list)
    target_users: list[str] = field(default_factory=list)
    training_data_description: str = ""
    training_data_stats: dict[str, str] = field(default_factory=dict)
    metrics: list[MetricInfo] = field(default_factory=list)
    performance_by_group: list[GroupPerformance] = field(default_factory=list)
    limitations: list[str] = field(default_factory=list)
    bias_considerations: list[str] = field(default_factory=list)
    risk_mitigations: list[str] = field(default_factory=list)
    contact: str = ""
    update_frequency: str = "Quarterly"

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "version": self.version,
            "date": self.date,
            "owner": self.owner,
            "model_type": self.model_type,
            "description": self.description,
            "intended_uses": self.intended_uses,
            "metrics": [{"name": m.name, "value": m.value} for m in self.metrics],
            "limitations": self.limitations,
        }


class ModelCardGenerator:
    """Generate model cards from configuration."""

    def __init__(self, templates_dir: str | Path | None = None):
        if templates_dir:
            self.env = Environment(
                loader=FileSystemLoader(str(templates_dir)),
                autoescape=select_autoescape(),
            )
        else:
            self.env = Environment(autoescape=select_autoescape())

    def generate(self, data: ModelCardData) -> str:
        """Generate a model card as Markdown."""
        template = self.env.from_string(MODEL_CARD_TEMPLATE)
        return template.render(model=data)

    def generate_from_yaml(self, config_path: str | Path) -> str:
        """Generate model card from a YAML configuration file."""
        path = Path(config_path)
        config = yaml.safe_load(path.read_text())
        data = self._parse_config(config)
        return self.generate(data)

    def generate_from_dict(self, config: dict[str, Any]) -> str:
        """Generate model card from a dictionary."""
        data = self._parse_config(config)
        return self.generate(data)

    def _parse_config(self, config: dict[str, Any]) -> ModelCardData:
        metrics = [
            MetricInfo(name=m["name"], value=str(m["value"]), description=m.get("description", ""))
            for m in config.get("metrics", [])
        ]
        groups = [
            GroupPerformance(group=g["group"], metric=g["metric"], value=str(g["value"]))
            for g in config.get("performance_by_group", [])
        ]
        return ModelCardData(
            name=config.get("name", "Unnamed Model"),
            version=config.get("version", "1.0"),
            date=config.get("date", datetime.now().strftime("%Y-%m-%d")),
            owner=config.get("owner", ""),
            model_type=config.get("model_type", ""),
            architecture=config.get("architecture", ""),
            framework=config.get("framework", ""),
            license=config.get("license", "Proprietary"),
            description=config.get("description", ""),
            intended_uses=config.get("intended_uses", []),
            out_of_scope_uses=config.get("out_of_scope_uses", []),
            target_users=config.get("target_users", []),
            training_data_description=config.get("training_data_description", ""),
            training_data_stats=config.get("training_data_stats", {}),
            metrics=metrics,
            performance_by_group=groups,
            limitations=config.get("limitations", []),
            bias_considerations=config.get("bias_considerations", []),
            risk_mitigations=config.get("risk_mitigations", []),
            contact=config.get("contact", ""),
            update_frequency=config.get("update_frequency", "Quarterly"),
        )


def main():
    parser = argparse.ArgumentParser(description="Model Card Generator")
    parser.add_argument("--config", required=True, help="YAML config path")
    parser.add_argument("--output", default=None, help="Output file path")
    args = parser.parse_args()

    generator = ModelCardGenerator()
    card = generator.generate_from_yaml(args.config)

    if args.output:
        Path(args.output).write_text(card)
        print(f"Model card written to {args.output}")
    else:
        print(card)


if __name__ == "__main__":
    main()
